using System.Text;

namespace Mini;

public enum Ty { Int, Bool }

/// Writes Tessera source for a Mini program. Ints are S64, and `main` returns S32.
public sealed class Emitter
{
    private readonly Dictionary<string, Function> _functions;
    private readonly StringBuilder _out = new();

    private Emitter(List<Function> program)
    {
        _functions = [];
        foreach (var f in program)
            if (!_functions.TryAdd(f.Name, f)) throw new MiniError(f.Line, $"function '{f.Name}' is defined twice");
        if (!_functions.TryGetValue("main", out var main)) throw new MiniError(1, "there is no 'main' function");
        if (main.Params.Count > 0) throw new MiniError(main.Line, "'main' takes no parameters");
    }

    public static string Emit(List<Function> program, string sourceName)
    {
        var e = new Emitter(program);
        e._out.Append($"// Generated by Mini from {sourceName}. Do not edit; edit the .mini file and regenerate.\n");
        foreach (var f in program)
        {
            e._out.Append('\n');
            e.EmitFunction(f);
        }
        return e._out.ToString();
    }

    // ── Types ───────────────────────────────────────────────────────────────

    private Dictionary<string, Ty> _types = [];

    private void InferTypes(Function f)
    {
        _types = f.Params.ToDictionary(p => p, _ => Ty.Int);
        void Walk(List<Stmt> stmts)
        {
            foreach (var s in stmts)
            {
                switch (s)
                {
                    case Let l: _types[l.Name] = TypeOf(l.Value); break;
                    case Assign a:
                        if (_types.TryGetValue(a.Name, out var t) && TypeOf(a.Value) != t)
                            throw new MiniError(a.Line, $"'{a.Name}' is {Show(t)}, but this assigns {Show(TypeOf(a.Value))}");
                        break;
                    case While w: Want(w.Cond, Ty.Bool, "a while condition"); Walk(w.Body); break;
                    case If i:
                        Want(i.Cond, Ty.Bool, "an if condition");
                        Walk(i.Then);
                        if (i.Else is not null) Walk(i.Else);
                        break;
                    case Return r: Want(r.Value, Ty.Int, "a return value"); break;
                    case Print p: Want(p.Value, Ty.Int, "print"); break;
                    case ExprStmt x: TypeOf(x.Value); break;
                }
            }
        }
        Walk(f.Body);
    }

    private static string Show(Ty t) => t == Ty.Int ? "an integer" : "a boolean";

    private void Want(Expr e, Ty want, string what)
    {
        if (TypeOf(e) != want) throw new MiniError(e.Line, $"{what} must be {Show(want)}");
    }

    private Ty TypeOf(Expr e)
    {
        switch (e)
        {
            case IntLit: return Ty.Int;
            case BoolLit: return Ty.Bool;
            case Var v:
                return _types.TryGetValue(v.Name, out var t) ? t : throw new MiniError(v.Line, $"'{v.Name}' is not declared");
            case Unary { Op: "-" } u: Want(u.Operand, Ty.Int, "'-'"); return Ty.Int;
            case Unary u: Want(u.Operand, Ty.Bool, "'!'"); return Ty.Bool;
            case Binary { Op: "&&" or "||" } b:
                Want(b.Left, Ty.Bool, $"'{b.Op}'");
                Want(b.Right, Ty.Bool, $"'{b.Op}'");
                return Ty.Bool;
            case Binary { Op: "==" or "!=" } b:
                if (TypeOf(b.Left) != TypeOf(b.Right)) throw new MiniError(b.Line, $"'{b.Op}' compares values of one type");
                return Ty.Bool;
            case Binary b:
                Want(b.Left, Ty.Int, $"'{b.Op}'");
                Want(b.Right, Ty.Int, $"'{b.Op}'");
                return b.Op is "<" or "<=" or ">" or ">=" ? Ty.Bool : Ty.Int;
            case Call c:
                if (!_functions.TryGetValue(c.Name, out var f)) throw new MiniError(c.Line, $"there is no function '{c.Name}'");
                if (c.Name == "main") throw new MiniError(c.Line, "'main' can't be called");
                if (f.Params.Count != c.Args.Count)
                    throw new MiniError(c.Line, $"'{c.Name}' takes {f.Params.Count} argument(s), got {c.Args.Count}");
                foreach (var a in c.Args) Want(a, Ty.Int, "an argument");
                return Ty.Int;
            default:
                throw new InvalidOperationException(e.GetType().Name);
        }
    }

    private static string Tess(Ty t) => t == Ty.Int ? "S64" : "Bool";

    // ── Routines ────────────────────────────────────────────────────────────

    private void EmitFunction(Function f)
    {
        InferTypes(f);
        var cfg = Cfg.Build(f);
        bool isMain = f.Name == "main";
        string ps = string.Join(", ", f.Params.Select(p => $"%{p}: S64"));
        _out.Append($"routine {f.Name}({ps}) -> {(isMain ? "S32" : "S64")}\n");
        var emitted = Emitted(cfg, isMain);
        bool first = true;
        foreach (var b in cfg.Blocks.Where(emitted.Contains))
        {
            if (!first) _out.Append('\n');
            first = false;
            new BlockWriter(this, cfg, b, isMain).Write();
        }
    }

    // ── Pass-through blocks ─────────────────────────────────────────────────
    //
    // A block that only copies variables and then jumps or returns needs no code of its own: an edge into it goes
    // straight to where it leads, with the copies applied to the arguments, and a return becomes an inline
    // `return(...)` arm. That is what the Style Guide asks of hand-written code, and it costs a generator nothing
    // once it tracks which value each variable holds.

    private static bool IsCopy(Expr x) => x is Var or IntLit or BoolLit or Unary { Op: "-", Operand: IntLit };

    private static bool PassesThrough(BasicBlock b, bool isMain) =>
        b.Name != "entry"
        && b.Code.All(s => s is Let { Value: var l } && IsCopy(l) || s is Assign { Value: var a } && IsCopy(a))
        && b.Term switch
        {
            Goto => true,
            Ret { Value: null } => true,
            Ret { Value: var v } => IsCopy(v!),
            _ => false,
        };

    /// Where an edge into `b` really lands: the first block that isn't a pass-through, or null for a return.
    private static BasicBlock? Landing(BasicBlock b, bool isMain)
    {
        for (int hops = 0; PassesThrough(b, isMain); hops++)
        {
            if (b.Term is not Goto g || hops > 1000) return null;
            b = g.Target;
        }
        return b;
    }

    private static HashSet<BasicBlock> Emitted(Cfg cfg, bool isMain)
    {
        var emitted = new HashSet<BasicBlock>();
        var work = new Stack<BasicBlock>([cfg.Blocks[0]]);
        while (work.TryPop(out var b))
        {
            if (!emitted.Add(b)) continue;
            foreach (var s in b.Successors)
                if (Landing(s, isMain) is { } landing) work.Push(landing);
        }
        return emitted;
    }

    /// The parameters of a block: its live-in variables, in declaration order.
    private static List<string> ParamsOf(Cfg cfg, BasicBlock b) =>
        b.Name == "entry" ? [] : cfg.Variables.Where(b.LiveIn.Contains).ToList();

    /// Emits one block. Variables map to the SSA value holding them right now; a block starts from its parameters
    /// (and the routine's invariant parameters), so nothing leaks in from other blocks.
    private sealed class BlockWriter(Emitter e, Cfg cfg, BasicBlock block, bool isMain)
    {
        private readonly Dictionary<string, string> _env = [];
        private readonly HashSet<string> _bound = [];
        private readonly StringBuilder _o = e._out;

        public void Write()
        {
            var ps = ParamsOf(cfg, block);
            _o.Append($"    block {block.Name}({string.Join(", ", ps.Select(p => $"%{p}: {Tess(e._types[p])}"))}):\n");
            foreach (var p in cfg.Source.Params) _env[p] = $"%{p}";   // routine parameters
            foreach (var p in ps)
            {
                _env[p] = $"%{p}";
                _bound.Add(p);
            }
            foreach (var s in block.Code) Statement(s);
            Terminator(block.Term!);
        }

        private void Line(string text) => _o.Append($"        {text}\n");

        /// The text of an edge into `target`: `name(args)`, or `return(x)` when the edge ends in a return.
        private string Edge(BasicBlock target, Dictionary<string, string> env)
        {
            if (!PassesThrough(target, isMain))
                return $"{target.Name}({string.Join(", ", ParamsOf(cfg, target).Select(p => env[p]))})";
            var inner = new Dictionary<string, string>(env);
            foreach (var s in target.Code)
            {
                var (name, value) = s switch
                {
                    Let l => (l.Name, l.Value),
                    Assign a => (a.Name, a.Value),
                    _ => throw new InvalidOperationException(),
                };
                inner[name] = CopyText(value, inner);
            }
            return target.Term switch
            {
                Goto g => Edge(g.Target, inner),
                Ret { Value: null } => "return(0)",
                Ret r => ReturnText(CopyText(r.Value!, inner)),
                _ => throw new InvalidOperationException(),
            };
        }

        private static string CopyText(Expr x, Dictionary<string, string> env) => x switch
        {
            Var v => env[v.Name],
            IntLit i => i.Value.ToString(),
            BoolLit b => b.Value ? "true" : "false",
            Unary { Operand: IntLit i } => (-i.Value).ToString(),
            _ => throw new InvalidOperationException(),
        };

        /// A fresh value name: `base`, then `base_2`, `base_3`, ... within this block.
        private string Fresh(string name)
        {
            string candidate = name;
            for (int n = 2; !_bound.Add(candidate); n++) candidate = $"{name}_{n}";
            return $"%{candidate}";
        }

        private void Statement(Stmt s)
        {
            switch (s)
            {
                case Let l: Define(l.Name, l.Value); break;
                case Assign a: Define(a.Name, a.Value); break;
                case Print p:
                    // A value or a chain goes in braces; a literal is already text.
                    string shown = IsSimple(p.Value) ? Operand(p.Value) : Chain(p.Value, lazy: false);
                    Line($"print_f(\"{(IsLiteralText(shown) ? shown : $"{{{shown}}}")}\\n\")");
                    break;
                case PrintStr p: Line($"print_f(\"{TemplateText(p.Text)}\\n\")"); break;
                case ExprStmt { Value: Call c }: Line(Chain(c, lazy: false)); break;
                case ExprStmt x: Operand(x.Value); break;   // evaluated for its panics, like a + b overflowing
            }
        }

        /// `x = expr`: a copy just renames (no code); anything else binds a value named after the variable.
        private void Define(string name, Expr value)
        {
            if (value is Var or IntLit or BoolLit)
            {
                _env[name] = Operand(value);
                return;
            }
            string v = Fresh(name);
            Line($"{v}: {Tess(e.TypeOf(value))} = {Chain(value, lazy: false)}");
            _env[name] = v;
        }

        private void Terminator(Terminator t)
        {
            switch (t)
            {
                case Goto g:
                    string edge = Edge(g.Target, _env);
                    Line(edge.StartsWith("return(") ? edge : $"jump {edge}");
                    break;
                case CondGoto c:
                    string cond = Value(c.Cond, "condition");
                    Line($"branch {cond} ? {Edge(c.IfTrue, _env)} : {Edge(c.IfFalse, _env)}");
                    break;
                case SelectGoto s:
                {
                    // Render every arm before writing `select:`, since a literal receiver may bind a line first.
                    var arms = s.Arms.Select(a => (Cond: Chain(a.Cond, lazy: true), Edge: Edge(a.Target, _env))).ToList();
                    string otherwise = Edge(s.Otherwise, _env);
                    int width = arms.Max(a => a.Cond.Length);
                    Line("when:");
                    foreach (var (condText, edgeText) in arms) Line($"    {condText.PadRight(width)} -> {edgeText}");
                    Line($"    {"_".PadRight(width)} -> {otherwise}");
                    break;
                }
                case Ret { Value: null }:
                    Line("return(0)");
                    break;
                case Ret r:
                    Line(ReturnText(IsSimple(r.Value!) ? Operand(r.Value!) : Chain(r.Value!, lazy: false)));
                    break;
            }
        }

        // ── Expressions ─────────────────────────────────────────────────────

        private static bool IsSimple(Expr x) => x is IntLit or BoolLit or Var or Unary { Op: "-", Operand: IntLit };

        /// One operation on simple operands: fine as an argument (`.bitand(%start.gt(0))`).
        private static bool IsShallow(Expr x) => IsSimple(x) || x switch
        {
            Binary b => IsSimple(b.Left) && IsSimple(b.Right),
            Unary u => IsSimple(u.Operand),
            Call c => c.Args.All(IsSimple),
            _ => false,
        };

        /// Literal text (`42`, `-5`, `true`), as opposed to a value name or a call.
        private static bool IsLiteralText(string s) => !s.StartsWith('%') && !s.EndsWith(')');

        /// An operand: a value name or a literal. Anything larger is bound to a named value first.
        private string Operand(Expr x) => IsSimple(x) ? Chain(x, lazy: false) : Bind(x);

        /// A value name, for a branch condition: a literal gets bound.
        private string Value(Expr x, string name)
        {
            string op = Operand(x);
            return op.StartsWith('%') ? op : BindText(op, e.TypeOf(x), name);
        }

        private string Bind(Expr x) => BindText(Chain(x, lazy: false), e.TypeOf(x), NameFor(x));

        private string BindText(string text, Ty type, string name)
        {
            string v = Fresh(name);
            Line($"{v}: {Tess(type)} = {text}");
            return v;
        }

        /// `return(x)`; main returns S32, so a value is converted there (a literal just takes the type).
        private string ReturnText(string operand) =>
            isMain && !IsLiteralText(operand) ? $"return({operand}.to_s32())" : $"return({operand})";

        /// An expression as one chain of calls, `%i.rem(15).eq(0)`. Eagerly (`lazy: false`), an argument that is
        /// itself an operation is bound first, keeping one level of nesting as the Style Guide asks, and the left
        /// side is bound before it so Mini's left-to-right order holds. In a select arm (`lazy: true`) only literals
        /// are bound, because an arm's condition runs only after the arms before it failed.
        private string Chain(Expr x, bool lazy) => x switch
        {
            IntLit i => i.Value.ToString(),
            BoolLit b => b.Value ? "true" : "false",
            Unary { Op: "-", Operand: IntLit i } => (-i.Value).ToString(),
            Var v => _env[v.Name],
            Unary { Op: "-" } u => $"{Receiver(u.Operand, lazy)}.neg()",
            Unary u => $"{Receiver(u.Operand, lazy)}.bitnot()",
            Binary b => BinaryText(b, lazy),
            Call c => CallChain(c, lazy),
            _ => throw new InvalidOperationException(x.GetType().Name),
        };

        /// A receiver with no argument to take a type from (`.neg()`, `.bitnot()`): a literal is bound.
        private string Receiver(Expr x, bool lazy)
        {
            string text = Chain(x, lazy);
            return IsLiteralText(text) ? BindText(text, e.TypeOf(x), "value") : text;
        }

        /// Arguments stay inline while they're shallow; if one is deeper, every non-simple argument is bound, in
        /// order, so calls inside them still run left to right.
        private string CallChain(Call c, bool lazy)
        {
            bool bindAll = !lazy && !c.Args.All(IsShallow);
            var args = c.Args.Select(a => bindAll ? Operand(a) : Chain(a, lazy));
            return $"{c.Name}({string.Join(", ", args)})";
        }

        private string BinaryText(Binary b, bool lazy)
        {
            string left, right;
            if (!lazy && !IsShallow(b.Right))
            {
                left = Operand(b.Left);
                right = Bind(b.Right);
            }
            else
            {
                left = Chain(b.Left, lazy);
                right = Chain(b.Right, lazy);
            }
            // A literal receiver takes its type from the argument (`3.sub(%n)`), but two literals have none, and
            // `-3.sub(...)` would read as a negation, so those receivers are bound.
            if (IsLiteralText(left) && (IsLiteralText(right) || left.StartsWith('-')))
                left = BindText(left, e.TypeOf(b.Left), "left");
            return $"{left}.{Method(b.Op)}({right})";
        }

        /// Mini text inside a Tessera `print_f` string: braces are doubled and backslashes escaped.
        private static string TemplateText(string text) =>
            text.Replace("\\", "\\\\").Replace("{", "{{").Replace("}", "}}");


        private static string Method(string op) => op switch
        {
            "+" => "add", "-" => "sub", "*" => "mul", "/" => "div", "%" => "rem",
            "==" => "eq", "!=" => "ne", "<" => "lt", "<=" => "le", ">" => "gt", ">=" => "ge",
            "&&" => "bitand", "||" => "bitor",
            _ => throw new InvalidOperationException(op),
        };

        /// Temporaries are named for what they hold, so the output reads like hand-written Tessera.
        private static string NameFor(Expr x) => x switch
        {
            Binary b => b.Op switch
            {
                "+" => "sum", "-" => "difference", "*" => "product", "/" => "quotient", "%" => "remainder",
                "==" => "is_equal", "!=" => "is_different", "<" => "is_less", "<=" => "is_at_most",
                ">" => "is_greater", ">=" => "is_at_least", "&&" => "both", _ => "either",
            },
            Unary { Op: "-" } => "negated",
            Unary => "is_not",
            Call c => c.Name,
            _ => "value",
        };
    }
}
